# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - git submodule init
  - git submodule update
  - npm install

build: off

test_script:
  - npm test
  - npm run-script coverage
